import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {
  AiFillLinkedin,
  AiFillGithub
} from "react-icons/ai";
import Image from "next/image";
import pfp from "../public/pfp_smaller.jpg"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Kevin Petow Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>developedbyKev</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill className='cursor-pointer text-2xl'/></li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-black px-4 py-2 rounded-lg ml-8 font-burtons' href='#'>Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-5'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium'>Kevin Petow</h2>
            <h3 className='text-2xl py-2'>Software Engineer</h3>
            <p className='text-md py-2 text-gray-800'>
              Full Stack Software Engineer developing web applications in Microsoft Azure.
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-10 py-3 text-gray-600'>
            <a href='https://www.linkedin.com/in/kevinpetow/' target='_blank' rel="noopener noreferrer"><AiFillLinkedin /></a>
            <a href="https://github.com/runkev" target='_blank' rel="noopener noreferrer"><AiFillGithub /></a> 
          </div>
          <div>
            <Image src={pfp} className='mx-auto rounded-full w-60 drop-shadow-2xl' alt='pfp'/>
          </div>
        </section>
      </main>

    </div>
  );
}
